[package]
name = "emale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs" 

[[bin]]
path="src/main.rs"
name="emale"

[dependencies]
actix-web="4"
actix-http="3"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
actix-rt = "2.7.0"
reqwest = { version = "0.11.10", features = ["json"] }
tokio = "1.17.0"
