# https://github.com/johnthagen/min-sized-rust#strip-symbols-from-binary
# Builder stage, to generate a compiled binary
FROM lukemathwalker/cargo-chef:latest-rust-1.63.0 as chef

WORKDIR /app
RUN apt update && apt install lld clang -y

## Layer caching with cargo-chef 

FROM chef as planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef as builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

COPY ..
ENV SQLX_OFFLINE true
RUN cargo build --release --bin emale

# use rust alpine, check https://github.com/emk/rust-musl-builder
# for generating tiny Docker images

# Runtime stageto run the binary
FROM debian:bullseye-slim AS runtime

WORKDIR /app

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl ca-certificates \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*


# Copy compiled binary from bulider environment
# to runtime environment
COPY --from=builder /app/target/release/emale emale
COPY configuration configuration
ENV APP_ENVIRONMENT production
ENTRYPOINT ["./emale"]