[package]
name = "imexcenger"
version = "0.1.0"
authors = ["ncnocap <ncnocap@gmail.com>"]
edition = "2021"

[dependencies]
image = "0.24.3"
num-complex = "0.2.1"
clap = { version = "3.2.16", features = ["derive", "cargo"] }